//! Every UI mark the Rust clients draw: [Lucide](https://lucide.dev) v0.462.0 (ISC — see
//! THIRD-PARTY-NOTICES.txt), each icon carried as its 24×24 SVG path data, every shape of
//! the master SVG folded into one path string.
//!
//! The Skia console parses these with Skia and the GTK shell with `gsk::Path`, both stroking
//! at Lucide's native width 2 with round caps and joins — so one mark cannot come out
//! differently on the two shells. The WinUI shell cannot draw a path at all (windows-reactor
//! has no vector element) and consumes the PNGs baked from the same masters instead.
//!
//! GENERATED by `scripts/gen-lucide-assets.sh` from `assets/lucide/*.svg` — do not edit.

/// Lucide `arrow-left`.
pub const ARROW_LEFT: &str = "M12 19l-7-7 7-7M19 12H5";
/// Lucide `arrow-right`.
pub const ARROW_RIGHT: &str = "M5 12h14M12 5l7 7-7 7";
/// Lucide `chart-column`.
pub const CHART_COLUMN: &str = "M3 3v16a2 2 0 0 0 2 2h16M18 17V9M13 17V5M8 17v-3";
/// Lucide `check`.
pub const CHECK: &str = "M20 6 9 17l-5-5";
/// Lucide `chevron-down`.
pub const CHEVRON_DOWN: &str = "M6 9l6 6 6-6";
/// Lucide `chevron-left`.
pub const CHEVRON_LEFT: &str = "M15 18l-6-6 6-6";
/// Lucide `chevron-right`.
pub const CHEVRON_RIGHT: &str = "M9 18l6-6-6-6";
/// Lucide `chevron-up`.
pub const CHEVRON_UP: &str = "M18 15l-6-6-6 6";
/// Lucide `circle-help`.
pub const CIRCLE_HELP: &str =
    "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3M12 17h.01";
/// Lucide `copy`.
pub const COPY: &str = "M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2zM4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2";
/// Lucide `corner-down-left`.
pub const CORNER_DOWN_LEFT: &str = "M9 10L4 15L9 20M20 4v7a4 4 0 0 1-4 4H4";
/// Lucide `ellipsis`.
pub const ELLIPSIS: &str = "M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0";
/// Lucide `gamepad-2`.
pub const GAMEPAD_2: &str = "M6 11L10 11M8 9L8 13M15 12L15.01 12M18 10L18.01 10M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z";
/// Lucide `keyboard`.
pub const KEYBOARD: &str = "M10 8h.01M12 12h.01M14 8h.01M16 12h.01M18 8h.01M6 8h.01M7 16h10M8 12h.01M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z";
/// Lucide `log-out`.
pub const LOG_OUT: &str = "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17L21 12L16 7M21 12L9 12";
/// Lucide `maximize`.
pub const MAXIMIZE: &str = "M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3";
/// Lucide `menu`.
pub const MENU: &str = "M4 12L20 12M4 6L20 6M4 18L20 18";
/// Lucide `mic-off`.
pub const MIC_OFF: &str = "M2 2L22 22M18.89 13.23A7.12 7.12 0 0 0 19 12v-2M5 10v2a7 7 0 0 0 12 5M15 9.34V5a3 3 0 0 0-5.68-1.33M9 9v3a3 3 0 0 0 5.12 2.12M12 19L12 22";
/// Lucide `mic`.
pub const MIC: &str =
    "M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3ZM19 10v2a7 7 0 0 1-14 0v-2M12 19L12 22";
/// Lucide `moon`.
pub const MOON: &str = "M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z";
/// Lucide `play`.
pub const PLAY: &str = "M6 3L20 12L6 21L6 3z";
/// Lucide `plus`.
pub const PLUS: &str = "M5 12h14M12 5v14";
/// Lucide `pointer`.
pub const POINTER: &str = "M22 14a8 8 0 0 1-8 8M18 11v-1a2 2 0 0 0-2-2a2 2 0 0 0-2 2M14 10V9a2 2 0 0 0-2-2a2 2 0 0 0-2 2v1M10 9.5V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v10M18 11a2 2 0 1 1 4 0v3a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15";
/// Lucide `power`.
pub const POWER: &str = "M12 2v10M18.4 6.6a9 9 0 1 1-12.77.04";
/// Lucide `refresh-cw`.
pub const REFRESH_CW: &str = "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8M21 3v5h-5M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16M8 16H3v5";
/// Lucide `rotate-cw`.
pub const ROTATE_CW: &str = "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8M21 3v5h-5";
/// Lucide `save`.
pub const SAVE: &str = "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zM17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7M7 3v4a1 1 0 0 0 1 1h7";
/// Lucide `send`.
pub const SEND: &str = "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11zM21.854 2.147l-10.94 10.939";
/// Lucide `settings`.
pub const SETTINGS: &str = "M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2zM9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0";
/// Lucide `square`.
pub const SQUARE: &str =
    "M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z";
/// Lucide `trash-2`.
pub const TRASH_2: &str = "M3 6h18M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2M10 11L10 17M14 11L14 17";
/// Lucide `undo-2`.
pub const UNDO_2: &str = "M9 14 4 9l5-5M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11";
/// Lucide `volume-2`.
pub const VOLUME_2: &str = "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298zM16 9a5 5 0 0 1 0 6M19.364 18.364a9 9 0 0 0 0-12.728";
/// Lucide `x`.
pub const X: &str = "M18 6 6 18M6 6l12 12";

/// Every icon, by its Lucide name — the key the shared slot table and the shells use.
pub const ALL: &[(&str, &str)] = &[
    ("arrow-left", ARROW_LEFT),
    ("arrow-right", ARROW_RIGHT),
    ("chart-column", CHART_COLUMN),
    ("check", CHECK),
    ("chevron-down", CHEVRON_DOWN),
    ("chevron-left", CHEVRON_LEFT),
    ("chevron-right", CHEVRON_RIGHT),
    ("chevron-up", CHEVRON_UP),
    ("circle-help", CIRCLE_HELP),
    ("copy", COPY),
    ("corner-down-left", CORNER_DOWN_LEFT),
    ("ellipsis", ELLIPSIS),
    ("gamepad-2", GAMEPAD_2),
    ("keyboard", KEYBOARD),
    ("log-out", LOG_OUT),
    ("maximize", MAXIMIZE),
    ("menu", MENU),
    ("mic-off", MIC_OFF),
    ("mic", MIC),
    ("moon", MOON),
    ("play", PLAY),
    ("plus", PLUS),
    ("pointer", POINTER),
    ("power", POWER),
    ("refresh-cw", REFRESH_CW),
    ("rotate-cw", ROTATE_CW),
    ("save", SAVE),
    ("send", SEND),
    ("settings", SETTINGS),
    ("square", SQUARE),
    ("trash-2", TRASH_2),
    ("undo-2", UNDO_2),
    ("volume-2", VOLUME_2),
    ("x", X),
];

/// One icon's path data by its Lucide name; `None` for a name this build does not ship.
pub fn path(name: &str) -> Option<&'static str> {
    ALL.iter().find(|(n, _)| *n == name).map(|(_, d)| *d)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every icon is reachable by its own name, the names are unique, and a name this
    /// build does not ship resolves to nothing rather than to the wrong mark.
    #[test]
    fn every_icon_is_reachable_by_name() {
        for (name, data) in ALL {
            assert_eq!(path(name), Some(*data), "{name}");
            assert!(!data.is_empty(), "{name} is empty");
        }
        let mut names: Vec<_> = ALL.iter().map(|(n, _)| *n).collect();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), ALL.len(), "a name is used twice");
        assert_eq!(path("no-such-icon"), None);
    }
}
