//! UI marks the clients draw: [Lucide](https://lucide.dev) v0.462.0 (ISC —
//! THIRD-PARTY-NOTICES.txt), in the two forms the shells need.
//!
//! **Path** — the master SVG folded into one 24×24 path string. Skia and GTK
//! both stroke it at Lucide's native width 2 with round caps and joins, so a
//! mark cannot render differently on the two shells.
//!
//! **Glyph** — the same icon's codepoint in Lucide's icon font. WinUI has no
//! vector element; a font glyph is the form that sizes and tints itself.
//!
//! Generated by `scripts/gen-lucide-assets.sh` from `assets/lucide/` — do not edit.

pub const ARROW_LEFT: &str = "M12 19l-7-7 7-7M19 12H5";
pub const ARROW_RIGHT: &str = "M5 12h14M12 5l7 7-7 7";
pub const CHART_COLUMN: &str = "M3 3v16a2 2 0 0 0 2 2h16M18 17V9M13 17V5M8 17v-3";
pub const CHECK: &str = "M20 6 9 17l-5-5";
pub const CHEVRON_DOWN: &str = "M6 9l6 6 6-6";
pub const CHEVRON_LEFT: &str = "M15 18l-6-6 6-6";
pub const CHEVRON_RIGHT: &str = "M9 18l6-6-6-6";
pub const CHEVRON_UP: &str = "M18 15l-6-6-6 6";
pub const CIRCLE_HELP: &str =
    "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3M12 17h.01";
pub const COPY: &str = "M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2zM4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2";
pub const CORNER_DOWN_LEFT: &str = "M9 10L4 15L9 20M20 4v7a4 4 0 0 1-4 4H4";
pub const ELLIPSIS: &str = "M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0";
pub const GAMEPAD_2: &str = "M6 11L10 11M8 9L8 13M15 12L15.01 12M18 10L18.01 10M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z";
pub const KEYBOARD: &str = "M10 8h.01M12 12h.01M14 8h.01M16 12h.01M18 8h.01M6 8h.01M7 16h10M8 12h.01M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z";
pub const LOG_OUT: &str = "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17L21 12L16 7M21 12L9 12";
pub const MAXIMIZE: &str = "M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3";
pub const MENU: &str = "M4 12L20 12M4 6L20 6M4 18L20 18";
pub const MIC_OFF: &str = "M2 2L22 22M18.89 13.23A7.12 7.12 0 0 0 19 12v-2M5 10v2a7 7 0 0 0 12 5M15 9.34V5a3 3 0 0 0-5.68-1.33M9 9v3a3 3 0 0 0 5.12 2.12M12 19L12 22";
pub const MIC: &str =
    "M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3ZM19 10v2a7 7 0 0 1-14 0v-2M12 19L12 22";
pub const MOON: &str = "M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z";
pub const PLAY: &str = "M6 3L20 12L6 21L6 3z";
pub const PLUS: &str = "M5 12h14M12 5v14";
pub const POINTER: &str = "M22 14a8 8 0 0 1-8 8M18 11v-1a2 2 0 0 0-2-2a2 2 0 0 0-2 2M14 10V9a2 2 0 0 0-2-2a2 2 0 0 0-2 2v1M10 9.5V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v10M18 11a2 2 0 1 1 4 0v3a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15";
pub const POWER: &str = "M12 2v10M18.4 6.6a9 9 0 1 1-12.77.04";
pub const REFRESH_CW: &str = "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8M21 3v5h-5M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16M8 16H3v5";
pub const ROTATE_CW: &str = "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8M21 3v5h-5";
pub const SAVE: &str = "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zM17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7M7 3v4a1 1 0 0 0 1 1h7";
pub const SEND: &str = "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11zM21.854 2.147l-10.94 10.939";
pub const SETTINGS: &str = "M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2zM9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0";
pub const SQUARE: &str =
    "M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z";
pub const TRASH_2: &str = "M3 6h18M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2M10 11L10 17M14 11L14 17";
pub const UNDO_2: &str = "M9 14 4 9l5-5M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11";
pub const VOLUME_2: &str = "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298zM16 9a5 5 0 0 1 0 6M19.364 18.364a9 9 0 0 0 0-12.728";
pub const X: &str = "M18 6 6 18M6 6l12 12";

pub const ALL: &[(&str, &str, char)] = &[
    ("arrow-left", ARROW_LEFT, '\u{e04c}'),
    ("arrow-right", ARROW_RIGHT, '\u{e04d}'),
    ("chart-column", CHART_COLUMN, '\u{e2a3}'),
    ("check", CHECK, '\u{e070}'),
    ("chevron-down", CHEVRON_DOWN, '\u{e071}'),
    ("chevron-left", CHEVRON_LEFT, '\u{e072}'),
    ("chevron-right", CHEVRON_RIGHT, '\u{e073}'),
    ("chevron-up", CHEVRON_UP, '\u{e074}'),
    ("circle-help", CIRCLE_HELP, '\u{e082}'),
    ("copy", COPY, '\u{e0a2}'),
    ("corner-down-left", CORNER_DOWN_LEFT, '\u{e0a5}'),
    ("ellipsis", ELLIPSIS, '\u{e0ba}'),
    ("gamepad-2", GAMEPAD_2, '\u{e0e2}'),
    ("keyboard", KEYBOARD, '\u{e284}'),
    ("log-out", LOG_OUT, '\u{e112}'),
    ("maximize", MAXIMIZE, '\u{e116}'),
    ("menu", MENU, '\u{e119}'),
    ("mic-off", MIC_OFF, '\u{e11d}'),
    ("mic", MIC, '\u{e11c}'),
    ("moon", MOON, '\u{e122}'),
    ("play", PLAY, '\u{e140}'),
    ("plus", PLUS, '\u{e141}'),
    ("pointer", POINTER, '\u{e1e8}'),
    ("power", POWER, '\u{e144}'),
    ("refresh-cw", REFRESH_CW, '\u{e149}'),
    ("rotate-cw", ROTATE_CW, '\u{e14d}'),
    ("save", SAVE, '\u{e151}'),
    ("send", SEND, '\u{e156}'),
    ("settings", SETTINGS, '\u{e158}'),
    ("square", SQUARE, '\u{e16b}'),
    ("trash-2", TRASH_2, '\u{e18e}'),
    ("undo-2", UNDO_2, '\u{e2a1}'),
    ("volume-2", VOLUME_2, '\u{e1ab}'),
    ("x", X, '\u{e1b2}'),
];

pub fn path(name: &str) -> Option<&'static str> {
    ALL.iter().find(|(n, _, _)| *n == name).map(|(_, d, _)| *d)
}

pub fn glyph(name: &str) -> Option<char> {
    ALL.iter().find(|(n, _, _)| *n == name).map(|(_, _, g)| *g)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_icon_is_reachable_by_name() {
        for (name, data, g) in ALL {
            assert_eq!(path(name), Some(*data), "{name}");
            assert_eq!(glyph(name), Some(*g), "{name}");
            assert!(!data.is_empty(), "{name} has no path");
            // Lucide's font puts every icon in the Private Use Area.
            assert!(
                ('\u{e000}'..='\u{f8ff}').contains(g),
                "{name}: {g:?} is not a private-use codepoint"
            );
        }
        let mut names: Vec<_> = ALL.iter().map(|(n, _, _)| *n).collect();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), ALL.len(), "a name is used twice");
        let mut glyphs: Vec<_> = ALL.iter().map(|(_, _, g)| *g).collect();
        glyphs.sort_unstable();
        glyphs.dedup();
        assert_eq!(glyphs.len(), ALL.len(), "two icons share a glyph");
        assert_eq!(path("no-such-icon"), None);
        assert_eq!(glyph("no-such-icon"), None);
    }
}
