#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — bring the punktfunk Nix binary cache at https://nix.unom.io live.
#
# Everything here is a step only a human can take: a Cloudflare record, a vhost in another
# repo, a Gitea secret. The wizard opens each page, says exactly what to click, and then
# VERIFIES the result before moving on — each stage has a distinct failure signature and
# they are easy to confuse (see the notes in each).
#
# Safe to re-run: every stage detects work already done and offers to skip.
# Full context: packaging/nix/README.md § "Cache infrastructure (maintainers)".
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

CACHE_HOST="nix.unom.io"
CACHE_PORT=3250
KEY_NAME="punktfunk-cache-1"
GITEA_REPO="https://git.unom.io/unom/punktfunk"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# nix_run ARGS… — run a new-style nix command, from a local nix if there is one, otherwise
# from the official image. Keeps this wizard usable on a machine with no nix (the maintainer
# box is macOS).
nix_run() {
  if command -v nix >/dev/null 2>&1; then
    nix --extra-experimental-features nix-command "$@"
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm -i nixos/nix nix --extra-experimental-features nix-command "$@"
  else
    return 127
  fi
}

banner "punktfunk Nix binary cache — bring-up"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "DNS — point $CACHE_HOST at unom-1"

# Derive the target from a sibling service rather than hardcoding an IP that can move.
TARGET_IP="$(dig +short flatpak.unom.io | tail -n1)"
[[ -n "$TARGET_IP" ]] || TARGET_IP="167.233.145.172"

CURRENT="$(dig +short "$CACHE_HOST" | tail -n1)"
if [[ "$CURRENT" == "$TARGET_IP" ]]; then
  say "$CACHE_HOST already resolves to $TARGET_IP — nothing to do."
  pause "Press Enter for the next stage"
else
  say "unom-1 (the hcloud box) is $TARGET_IP — the same address flatpak.unom.io uses."
  open_url "https://dash.cloudflare.com/?to=/:account/unom.io/dns/records"
  step "Add record → Type: A"
  step "Name: nix        (Cloudflare appends the zone, giving $CACHE_HOST)"
  step "IPv4 address: $TARGET_IP"
  step "Proxy status: DNS only — click the orange cloud so it turns GREY."
  warn "Proxied (orange) would break large NAR downloads and mask the origin's 404s,"
  note "  which nix needs in order to treat a miss as a miss rather than a hard error."
  step "Save."
  pause "Saved? Press Enter to verify"

  for _ in 1 2 3 4 5 6 7 8 9 10; do
    CURRENT="$(dig +short "$CACHE_HOST" | tail -n1)"
    [[ -n "$CURRENT" ]] && break
    printf '  %swaiting for DNS to propagate…%s\n' "$DIM" "$RESET"
    sleep 6
  done
  if [[ "$CURRENT" == "$TARGET_IP" ]]; then
    printf '  %s✓%s %s → %s\n' "$GREEN" "$RESET" "$CACHE_HOST" "$CURRENT"
  elif [[ -n "$CURRENT" ]]; then
    warn "$CACHE_HOST resolves to $CURRENT, expected $TARGET_IP."
    note "  If that is a Cloudflare address (104.x / 172.6x), the record is PROXIED — grey the cloud."
    confirm "Continue anyway?" || exit 1
  else
    warn "$CACHE_HOST still does not resolve."
    SKIPPED+=("DNS record for $CACHE_HOST")
    confirm "Continue anyway?" || exit 1
  fi
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Caddy vhost — terminate TLS for $CACHE_HOST"

say "The edge Caddy runs on unom-1 itself, and its config is VERSION CONTROLLED in unom/infra."
printf '\n'
warn "Do NOT edit ~/caddy/Caddyfile on the box."
note "  That file looks like the config but is a copy deploy-all.sh rsyncs over from unom/infra,"
note "  with no .git there to warn you. A vhost added only on the box survives until the next"
note "  deploy and no longer — that is how the winget source vanished on 2026-07-26."
printf '\n'
say "Add this next to the existing docs.punktfunk.unom.io block, in caddy/Caddyfile:"
printf '\n'
printf '      %s%s {\n          import security_headers\n          reverse_proxy localhost:%s\n      }%s\n\n' \
  "$DIM" "$CACHE_HOST" "$CACHE_PORT" "$RESET"
open_url "https://git.unom.io/unom/infra"
step "Edit caddy/Caddyfile, add the block above, commit and push."
step "Apply it the way unom/infra normally deploys (deploy-all)."
pause "Applied? Press Enter to verify the certificate"

# Diagnose by SNI. Caddy 308s EVERY Host on :80 to https, including names it has never heard
# of, so a redirect there proves nothing at all.
TLS_OUT="$(openssl s_client -connect "${CACHE_HOST}:443" -servername "$CACHE_HOST" \
            </dev/null 2>&1 | grep -E '^subject=|alert' | head -n3 || true)"
if printf '%s' "$TLS_OUT" | grep -q '^subject='; then
  printf '  %s✓%s Caddy is serving a certificate for %s\n' "$GREEN" "$RESET" "$CACHE_HOST"
else
  warn "No certificate for $CACHE_HOST yet:"
  printf '      %s%s%s\n' "$DIM" "${TLS_OUT:-(no response)}" "$RESET"
  note "  Expected before the vhost is applied — Caddy cannot present a cert for a name it"
  note "  does not serve. If you DID apply it, the deploy likely never reached the box."
  SKIPPED+=("Caddy vhost for $CACHE_HOST in unom/infra caddy/Caddyfile")
  confirm "Continue anyway?" || exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Start the cache container on unom-1"

say "deploy-services.yml places the compose file + Caddyfile + prune.sh and starts the"
say "container on port $CACHE_PORT. It serves an EMPTY cache until the first publish."
open_url "$GITEA_REPO/actions?workflow=deploy-services.yml"
step "Run workflow → leave the input blank → Run."
step "Wait for the nix-cache job to go green."
pause "Green? Press Enter to verify"

CODE="$(curl -sS -o /dev/null -w '%{http_code}' -m 15 "https://$CACHE_HOST/nix-cache-info" 2>/dev/null || echo 000)"
case "$CODE" in
  404)
    printf '  %s✓%s Cache is up and empty — 404 on every path, exactly right for an empty cache\n' "$GREEN" "$RESET" ;;
  200)
    printf '  %s✓%s Cache is up and already holds content\n' "$GREEN" "$RESET" ;;
  502|503)
    warn "Caddy answered $CODE — the vhost is live but nothing is listening on :$CACHE_PORT."
    note "  Check the nix-cache job in deploy-services.yml, or docker compose ps on unom-1."
    SKIPPED+=("cache container on unom-1:$CACHE_PORT")
    confirm "Continue anyway?" || exit 1 ;;
  *)
    warn "Unexpected response ($CODE) from https://$CACHE_HOST/nix-cache-info"
    SKIPPED+=("cache container on unom-1:$CACHE_PORT")
    confirm "Continue anyway?" || exit 1 ;;
esac

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Signing key — generate it, store it, pin it"

README_MD="$REPO_ROOT/packaging/nix/README.md"
INSTALL_MD="$REPO_ROOT/docs-site/content/docs/install.md"

if ! grep -q "$KEY_NAME:<" "$README_MD" 2>/dev/null; then
  say "The docs already carry a real public key, so a key has been generated before."
  warn "A new key would invalidate every signature already published."
  if ! confirm "Generate a REPLACEMENT key anyway?"; then
    say "Keeping the existing key."
    SKIP_KEY=1
    pause "Press Enter for the last stage"
  fi
fi

if [[ "${SKIP_KEY:-0}" != 1 ]]; then
  say "Generating an ed25519 signing key pair…"
  SECRET_KEY="$(nix_run key generate-secret --key-name "$KEY_NAME" 2>/dev/null || true)"
  if [[ -z "$SECRET_KEY" ]]; then
    warn "Could not run nix here (no local nix, and no docker to fall back to)."
    say "Generate it on any Nix box and paste it back:"
    note "  nix key generate-secret --key-name $KEY_NAME"
    ask_secret SECRET_KEY "Paste the secret key line:"
  fi

  if [[ -z "$SECRET_KEY" ]]; then
    SKIPPED+=("NIX_CACHE_SIGNING_KEY secret + public key in the docs")
  else
    PUBLIC_KEY="$(printf '%s' "$SECRET_KEY" | nix_run key convert-secret-to-public 2>/dev/null || true)"

    printf '\n  %sSecret key — paste this into Gitea now; nothing here keeps a copy:%s\n\n' "$BOLD" "$RESET"
    printf '      %s\n\n' "$SECRET_KEY"
    open_url "$GITEA_REPO/settings/actions/secrets"
    step "Add Secret → Name: NIX_CACHE_SIGNING_KEY"
    step "Value: the whole line above, including the '$KEY_NAME:' prefix."
    step "Add Secret."
    warn "This is the only copy — it is never written to disk."
    pause "Stored? Press Enter"
    WRITTEN_SECRET+=("NIX_CACHE_SIGNING_KEY (Gitea)")
    SECRET_KEY=""

    if [[ -n "$PUBLIC_KEY" ]]; then
      printf '\n  %sPublic key%s — this is what users pin:\n\n      %s\n\n' "$BOLD" "$RESET" "$PUBLIC_KEY"
      # Both docs carry a `punktfunk-cache-1:<…>` placeholder. Fill them in now rather than
      # making someone wait an hour for the first publish to print the same value.
      for f in "$README_MD" "$INSTALL_MD"; do
        [[ -f "$f" ]] || continue
        tmp="$(mktemp)"
        sed "s|${KEY_NAME}:<[^>]*>|${PUBLIC_KEY}|g" "$f" > "$tmp" && mv "$tmp" "$f"
        printf '  %s✓ pinned in%s %s\n' "$GREEN" "$RESET" "${f#"$REPO_ROOT"/}"
      done
      printf '\n'
      say "Commit those two files — without the key nobody can trust the cache."
    else
      warn "Could not derive the public key; the first publish prints it in its log."
      SKIPPED+=("public key in packaging/nix/README.md + docs-site install.md")
    fi
    pause "Press Enter for the last stage"
  fi
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Publish — land the flake on main and verify"

say "The publish tier runs on a push to main touching the flake, Cargo.*, or packaging/nix."
say "Merging the cache PR is exactly such a push, so it publishes on merge."
printf '\n'
note "  It builds the whole Rust workspace AND gamescope inside the nix sandbox — sccache"
note "  cannot reach in there, so budget roughly an hour for the first run."
note "  If it reddens on 'Build the bun packages', that is the known intermittent OOM"
note "  (exit 137) rather than a real break — re-run the job."
printf '\n'
open_url "$GITEA_REPO/pulls"
step "Merge the Nix binary cache PR."
step "Watch the nix workflow's 'Sign + publish to nix.unom.io' step."
pause "Published? Press Enter to verify the live cache"

CODE="$(curl -sS -o /dev/null -w '%{http_code}' -m 15 "https://$CACHE_HOST/nix-cache-info" 2>/dev/null || echo 000)"
if [[ "$CODE" == 200 ]]; then
  printf '  %s✓%s nix-cache-info is being served\n' "$GREEN" "$RESET"
  LIVE_PUB="$(curl -sS -m 15 "https://$CACHE_HOST/punktfunk-cache.pub" 2>/dev/null || true)"
  [[ -n "$LIVE_PUB" ]] && printf '  %s✓%s published public key: %s\n' "$GREEN" "$RESET" "$LIVE_PUB"
  # A cache that 200s on nix-cache-info but does not 404 a miss is the one failure mode that
  # breaks USERS rather than us: nix reads any non-404 as a hard error, not as a cache miss.
  MISS="$(curl -sS -o /dev/null -w '%{http_code}' -m 15 \
    "https://$CACHE_HOST/0000000000000000000000000000000000.narinfo" 2>/dev/null || echo 000)"
  if [[ "$MISS" == 404 ]]; then
    printf '  %s✓%s a miss returns 404 — nix falls through to cache.nixos.org correctly\n' "$GREEN" "$RESET"
  else
    warn "a miss returns $MISS, not 404 — every user build would then fail on any package"
    warn "this cache does not hold. Check for a proxy or auth layer in front of Caddy."
    SKIPPED+=("404-on-miss behaviour at $CACHE_HOST")
  fi
else
  warn "https://$CACHE_HOST/nix-cache-info returned $CODE — nothing published yet."
  SKIPPED+=("first publish to $CACHE_HOST")
fi

finish

printf '  %sUsers now add, on NixOS:%s\n\n' "$BOLD" "$RESET"
printf '      nix.settings = {\n'
printf '        substituters = [ "https://%s" ];\n' "$CACHE_HOST"
printf '        trusted-public-keys = [ "%s" ];\n' "${PUBLIC_KEY:-$KEY_NAME:…}"
printf '      };\n\n'
note "  Full instructions: packaging/nix/README.md § Binary cache"
printf '\n'
