# punktfunk-gamescope — gamescope carrying punktfunk's capture patches, installed under its own
# name so it sits BESIDE the distro's gamescope (Game Mode keeps using that one).
#
# This spec REPACKS a binary that was already built, rather than building gamescope itself: the
# build is a ~10-minute meson compile of an unrelated tree that CI already does once per Fedora
# major and caches (.gitea/workflows/rpm.yml). Rebuilding it inside rpmbuild would double that for
# no gain, and would need network access in the build root to fetch the upstream tree.
#
# The counterpart for Arch is packaging/gamescope/PKGBUILD, which DOES build from source, because
# makepkg fetches sources by design and the AUR-style recipe is what an Arch user expects.
#
# Usage: bash packaging/gamescope/build-gamescope-rpm.sh --stage <destdir-the-build-script-wrote>
Name:           punktfunk-gamescope
Version:        %{pf_version}
Release:        %{pf_release}%{?dist}
Summary:        gamescope with punktfunk's PipeWire capture patches (HDR, cursor, overlay, virtual-display modes)

# gamescope is BSD-2-Clause; our patches are contributed under the same terms.
License:        BSD-2-Clause
URL:            https://git.unom.io/unom/punktfunk
Source0:        punktfunk-gamescope
# The Vulkan WSI layer built from the same tree at the same rev as the compositor above. A game
# nested under gamescope gets its HDR10 swapchain from this layer and from nothing else, and a layer
# built for a DIFFERENT gamescope kills every Vulkan client — so the two ship together or the
# package is a trap.
Source1:        libVkLayer_PUNKTFUNK_gamescope_wsi.so
Source2:        punktfunk_gamescope_wsi.json

# Not `Provides: gamescope` and not `Conflicts:` either — this ships a differently-named binary and
# is designed to coexist. A box's Game Mode session keeps running the distro's gamescope; only the
# sessions punktfunk-host starts itself resolve this one (PUNKTFUNK_GAMESCOPE_BIN >
# punktfunk-gamescope > gamescope).
#
# The runtime library Requires are auto-generated by rpmbuild from the binary's ELF NEEDED entries,
# which is exactly right here: this binary is soname-coupled to the Fedora major it was compiled
# on, and the generated Requires are what stop it installing on the wrong one.
Recommends:     punktfunk-host

# Nothing is compiled here, so there is no debuginfo to extract; without this rpmbuild fails
# looking for sources it was never given.
%global debug_package %{nil}

%description
gamescope built from the upstream revision punktfunk pins, plus the patches in
packaging/gamescope/patches:

  * 10-bit BT.2020/PQ capture formats on the PipeWire node, so an HDR game reaches a capture
    consumer as HDR instead of pre-tonemapped SDR.
  * --pipewire-composite-cursor: paint the pointer into the capture stream, so a consumer with no
    cursor of its own gets one — and the host stops blending one in, which frees the encoder's
    fastest zero-copy source.
  * A headless session advertises its real mode and refresh rates (and --custom-refresh-rates), so
    Steam and games see the resolution and refresh the stream actually runs at instead of an
    unnamed 60 Hz panel.
  * --pipewire-composite-external-overlay: paint the mangoapp performance overlay into the capture
    stream, so the fps/stats readout is visible to someone watching remotely.

Installed as /usr/bin/punktfunk-gamescope, with its matching Vulkan WSI layer under
/usr/lib/punktfunk. The layer carries its own name and its own enable variable, so it sits beside
the one your gamescope package installs rather than replacing it, and only sessions punktfunk-host
starts switch to it. Your system gamescope is untouched.

%prep
# Nothing to unpack: Source0 IS the binary.

%build
# Nothing to build — see the header.

%install
install -Dm0755 %{SOURCE0} %{buildroot}%{_bindir}/punktfunk-gamescope

# /usr/lib, spelled literally rather than %{_libdir}, which is /usr/lib64 here. The layer's manifest
# carries an ABSOLUTE library_path baked in at build time (/usr/lib/punktfunk/...), so this path and
# that string have to agree or the loader finds a manifest pointing at nothing. Nothing links this
# .so by soname — the Vulkan loader dlopens it by that absolute path — so there is no multilib
# question to answer, and a private vendor directory is where it belongs.
install -Dm0755 %{SOURCE1} %{buildroot}/usr/lib/punktfunk/libVkLayer_PUNKTFUNK_gamescope_wsi.so
install -Dm0644 %{SOURCE2} %{buildroot}/usr/lib/punktfunk/vulkan/implicit_layer.d/punktfunk_gamescope_wsi.json

%check
# The marker is the host's entire capability probe (`gamescope_patch_level()`): a binary that lost
# the patches would install fine and then silently stream SDR with no cursor. Refuse to package it.
#
# Executed in the build root, which is the same container the binary was compiled in — if that ever
# stops being true this check is the thing that notices.
%{buildroot}%{_bindir}/punktfunk-gamescope --version 2>&1 | grep -q '+pfhdr' || {
  echo "punktfunk-gamescope: the +pfhdr marker is missing — the patches did not take" >&2
  exit 1
}

# The manifest's absolute library_path must name the file we actually installed. Getting this wrong
# (%{_libdir} on a multilib box, a renamed .so) produces a package that installs cleanly and then
# does nothing at all — the loader reads a manifest, finds no library, and moves on in silence.
LAYER_LIB="$(grep -o '"library_path"[[:space:]]*:[[:space:]]*"[^"]*"' \
  %{buildroot}/usr/lib/punktfunk/vulkan/implicit_layer.d/punktfunk_gamescope_wsi.json \
  | sed 's/.*"\(\/[^"]*\)".*/\1/')"
[ -f "%{buildroot}${LAYER_LIB}" ] || {
  echo "punktfunk-gamescope: the layer manifest points at ${LAYER_LIB}, which this package does" >&2
  echo "                     not install — games would silently get no HDR swapchain" >&2
  exit 1
}

%files
%{_bindir}/punktfunk-gamescope
/usr/lib/punktfunk/libVkLayer_PUNKTFUNK_gamescope_wsi.so
/usr/lib/punktfunk/vulkan/implicit_layer.d/punktfunk_gamescope_wsi.json

%changelog
# Generated per build; see the git history for the patch set's own changes.
